version: '3.2'
services:
  cli:
    tty: true
    container_name: switch
    command: tail -f /dev/null

    volumes:
      - $HOME/.kube:/root/.kube
      - .:/opt/meta
      - ./python3/packages/eusy_automation/eusy_automation:/opt/site-packages/eusy_automation
      - ./python3/packages/eusy_automation_aws/eusy_automation_aws:/opt/site-packages/eusy_automation_aws
      - ./python3/packages/eusy_cdk8s/eusy_cdk8s:/opt/site-packages/eusy_cdk8s
      - ./python3/packages/eusy_cdktf/eusy_cdktf:/opt/site-packages/eusy_cdktf
      - ./python3/packages/eusy_conf/eusy_conf:/opt/site-packages/eusy_conf
      - ./python3/packages/eusy_globals/eusy_globals:/opt/site-packages/eusy_globals
      - ./templates/.zshrc:/root/.zshrc
      - ./templates/ssh_config:/root/.ssh/config
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.aws:/root/.aws
      # - ${SSH_AUTH_SOCK}:/ssh-agent

    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - LOG_LEVEL=ERROR
      - DOCKER_BUILDKIT=1

    build:
      context: .
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: 3.18
        CDKTF_CLI_VERSION: 0.20.2
        CDK8S_CLI_VERSION: 2.198.9
        DYFF_VERSION: 1.5.6
        HELM_VERSION: 3.8.0
        IAM_AUTH_LINK: "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64"
        INSPEC_VERSION: 5.18.14
        ISTIO_VERSION: 1.17.2
        KUBECTL_VERSION: 1.26.1
        PIPENV_PACKAGE_VERSION: 2022.1.8
        PYCALL_VERSION: 1.4.1
        PYTHON_CUSTOM_VERSION: 3.9
        PYTHON_SETUPTOOLS_VERSION: 50.3.0
        TERRAFORM_VERSION: 1.4.6
