---
services:
  cli:
    tty: true
    container_name: arranger
    command: tail -f /dev/null

    volumes:
      - $HOME/.kube:/root/.kube
      - .:/opt/arranger
      - ./python3/packages/arranger_conf/arranger_conf:/opt/site-packages/arranger_conf
      - ./templates/.zshrc:/root/.zshrc
      - ./templates/ssh_config:/root/.ssh/config
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.aws:/root/.aws

    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - LOG_LEVEL=ERROR
      - DOCKER_BUILDKIT=1

    build:
      context: .
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: "3.20"
        CDKTF_CLI_VERSION: "0.20.9"
        CDK8S_CLI_VERSION: "2.198.254"
        DYFF_VERSION: "1.9.2"
        HELM_VERSION: "3.16.2"
        IAM_AUTH_VERSION: "0.6.27"
        INSPEC_VERSION: "5.18.14"
        ISTIO_VERSION: "1.23.3"
        KUBECTL_VERSION: "1.31.0"
        PIPENV_PACKAGE_VERSION: "2024.4.0"
        PYCALL_VERSION: "1.4.1"
        PYTHON_CUSTOM_VERSION: "3.11.10"
        PYTHON_SETUPTOOLS_VERSION: "75.3.0"
        TERRAFORM_VERSION: "1.9.8"
        TFENV_REMOTE: "https://hashicorp-releases.yandexcloud.net"

    image: arranger
