name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Lint Python Code with Black", "Lint Docker Compose YAML"]
    branches:
      - main
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          docker compose -f docker-compose.yml build
          docker tag arranger "ghcr.io/vsuzdaltsev/arranger:latest"
          docker push ghcr.io/vsuzdaltsev/arranger:latest
