name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Lint Docker Compose YAML", "Lint Python Code with Black"]
    branches:
      - main
    types:
      - completed

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
          -t ghcr.io/vsuzdaltsev/arranger:latest \
          --push .
