name: Build Python packages

on: [pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pipenv sync -d
          pipenv run inv python3.build-and-install

