name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ github.event_name == 'push' }}
        run: |
          docker compose -f docker-compose.yml build
          docker tag arranger "ghcr.io/vsuzdaltsev/arranger:latest"
          docker push ghcr.io/vsuzdaltsev/arranger:latest
