name: Generate k8s manifest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_run:
    workflows: ["Lint Docker Compose YAML", "Lint Python Code with Black"]
    branches:
      - main
    types:
      - completed

jobs:
  generate_k8s_manifest_for_d1:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker compose -f docker-compose.yml build

      - name: Generate k8s manifest
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' }}
        run: |
          docker compose up
          docker compose run --rm arranger /bin/bash -c "inv k8s.arranger-app.generate --environment d1 --services httpbin | yq e"