name: Generate k8s manifest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_run:
    workflows: ["Lint Docker Compose YAML", "Lint Python Code with Black"]
    branches:
      - main
    types:
      - completed

jobs:
  generate_k8s_manifest_for_d1:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker pull ghcr.io/vsuzdaltsev/arranger:latest

      - name: Generate k8s manifest
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' }}
        run: |
          docker compose up
          docker exec arranger /bin/bash -c "pipenv run inv k8s.arranger-app.generate --environment d1 --services httpbin"
