name: Lint Docker Compose YAML
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
      - name: Install yamllint
        run: |
          pip install yamllint
      - name: Lint docker-compose.yml
        run: |
          yamllint docker-compose.yml
