name: Lint Docker Compose YAML

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint docker-compose.yml
        run: |
          docker compose -f docker-compose.yml config --quiet 
