name: Pytest Specs

on: [pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pipenv sync -d
          pipenv run inv python3.build-and-install

      - name: Run Spec Invoke task
        run: |
          pipenv run inv spec.python
