name: Run Specs

on: [pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel
          pipenv sync -d
          pip install pyyaml pytest
          inv python3.build-and-install

      - name: Run invoke task
        run: |
          inv spec.python