name: Specs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_run:
    workflows: ["Lint Docker Compose YAML", "Lint Python Code with Black"]
    branches:
      - main
    types:
      - completed

jobs:
  pytest:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Specs
        run: |
          docker compose up -d
          docker exec arranger /bin/bash -c "pipenv run inv tf.list-stacks | jq"
          docker exec arranger /bin/bash -c "pipenv run inv tf.list-tenants | jq"
          docker exec arranger /bin/bash -c "pipenv run inv k8s.arranger-app.generate --environment d1 --services httpbin | yq e"
          docker exec arranger /bin/bash -c "pipenv run inv spec.python"
